
         function getValue()
            {
                var bank1= new Array("You caught a shiny guppy. ",
                                     "You caught a boot. 🥾",
                                     "You caught a treasure chest! 🧰",
                                     "You caught an angry octopus! 🐙",
                                     "You caught a cold. 🥶",
                                     "You caught a very old boot. 👢",
                                     "You caught a particularly fiesty crab. 🦀",
                                     "You caught a slimey squid. 🦑",
                                     "You caught a swordfish. 🤺",
                                     "You caught a flounder. 😑",
                                     "You caught a rainbow trout. 🌈",
                                     "You caught a speckled trout. ",
                                     "You caught a king salmon. ",
                                     "You caught a pissed off blowfish. 🐡",
                                     "You caught a onery oyster. 🦪",
                                     "You caught a squirting clam. 🐚",
                                     "You caught an empty leather wallet. 👛",
                                     "You caught a barracuda. ",
                                     "You caught a weird vibe, man. 😬",
                                     "You caught the feint smell of whiskey in the air. 🥃",
                                     "You caught a screaming seahorse. He is terrified of you. 🐴",
                                     "You caught an invisible sandwich. It is delicious, sort of; a little too salty. 🍽️",
                                     "You caught a beatboxing platypus. 💯",
                                     "You caught a head-banging hammerhead shark. 🦈",
                                     "You caught a norwal. 🦄",
                                     "You caught an aged tuft of unicorn hair. 🦄",
                                     "You caught a rusty can of sardines. 🥫",
                                     "You caught a grumpy, little fish. He doesn't like you very much. 😡",
                                     "You caught a baby seaturtle. HOW DARE YOU! You feel very bad about this. 🐢",
                                     "You caught the wrong end of an alleycat. 🙀",
                                     "You caught a seabunny. 🐰",
                                     "You caught a replica Van Gogh painting. 😱",
                                     "You caught a gallon of sour lemonade. 🍋",
                                     "You caught a bad case of the heebee geebees. 🤡",
                                     "You caught cabin fever. 🏚️",
                                     "You caught a an inch of saltwater taffy. 🍬",
                                     "You caught a crystal ball with a magical fairy trapped inside. 🔮",
                                     "You caught a dragon egg. 🥚",
                                     "You caught the spirit of Christmas trapped in a decomposing wool sock. 🎁",
                                     "You caught a twig that reminds you of your parents. 🍂",
                                     "You caught an ancient book of magic spells. 📖",
                                     "You caught a ship in a bottle. 🍾",
                                     "You caught the world's smallest tea set. ☕",
                                     "You caught a set of bagpipes covered in sword dancing barnacles. 🍀",
                                     "You caught a bottle of bourbon from 1907. 🍾",
                                     "You caught a vial of glacier water tied to a pearl necklace. 💧",
                                     "You caught a tattered oil painting of Henry VIII. 🖼️",
                                     "You caught a peck of pickled peppers. 🌶️",
                                     "You caught the drift. 🌬️",
                                     "You caught a glimpse of what is yet to come. 👀",
                                     "You caught a blue marlin. 🌊",
                                     "You caught an unraveling, old anchorline. ⛓️",
                                     "You caught a strange smell in the air. 🦨",
                                     "You caught a suitcase full of money. 💰",
                                     "You caught an overwhelming sense of self-confidence. 😎",
                                     "You caught the feeling that someone is always watching you. 😨",
                                     "You caught a rotting old bunch of bananas. 🍌",
                                     "You caught your friends talking about you behind your back. 🤬",
                                     "You caught a flight out of town to go river rafting with strangers. 🛫",
                                     "You caught a sudden sense of urgency but nothing's really happening. 🆘",
                                     "You caught an attitude with yourself and had to tell yourself to simmer down. 😤",
                                     "You caught Queen Elizabeth's immortality potion. 🧴",
                                     "You caught a vial of eastern-diamondback rattle snake venom. 🐍",
                                     "You caught a decaying string of ears. 👂",
                                     "You caught an old music box that plays country western hits of 1930s. 📻",
                                     "You caught a rusty treblehook. 🎼",
                                     "You caught a slingshot. Hey, it actually works pretty good! ",
                                     "You caught a broken time machine. ⏲️",
                                     "You caught an awful hankering to start a mosh pit. 🤘",
                                     "You caught a bag of marbles that you lost a long time ago. 🤪",
                                     "You caught a large ginseng root. ",
                                     "You caught a can of beans in meat sauce. 🥫",
                                     "You caught a newspaper from 1947. 📰",
                                     "You caught a brand new tuxedo jacket. 🤵",
                                     "You caught a little ride on the wild side. 🎢",
                                     "You caught a gross basketball sock. ⛹️‍♀️",
                                     "You caught all your hopes and dreams, but you can't figure out where to put them. 💭",
                                     "You caught medusa's heart. 🖤",
                                     "You caught some kind of baterial infection in your left ear. But you can still hear pretty good with your right. 🦻🏼",
                                     "You caught a triggerfish. 🔫",
                                     "You caught a pinfish. 🧷",
                                     "You caught them red-handed! You did always have your suspicions. 🙋‍♂️🙋‍♀️",
                                     "You caught a brand new pair of boots. Score! 🥾",
                                     "You caught a collection of fake ids. 💳",
                                     "You caught a stingray. 🦂",
                                     "You caught a baby alligator. 🐊",
                                     "You caught a small tiger shark. 🦈",
                                     "You caught a seagull in your cast, and watch it flail around on the ground. 😭",
                                     "You caught a rusty, old alarm clock. ⏰",
                                     "You caught a moldy, orange life-vest. 🦺",
                                     "You caught a jaunting electrical shock through your fishing pole... That was strange. ⚡",
                                     "You caught a bit of blue string. 🧵",
                                     "You caught half of a busted, old guitar. 🎸",
                                     "You caught a cold six-pack of beer. 🍻",
                                     "You caught a cheap bottle of wine. 🍷",
                                     "You caught an empty bottle of sherry. 🍷",
                                     "You thought that you caught something for a second, but you didn't. 😕",
                                     "You got a nibble. 😋",
                                     "You felt a little nibble. 🤗",
                                     "You started feeling a little hungry, so you had a snack. It was yummy. 😋",
                                     "You got thristy and drank some rain water from your water skin. 🌧️",
                                     "You caught wind of some bad news. 👎",
                                     "You caught on to them before they caught on to you. 💂",
                                     "You caught a tuna. 🐟",
                                     "You caught an alligator gar. ",
                                     "You caught a tiny octopus trying to steal your bait. 🐙",
                                     "You caught a plastic grocery bag. 🛍️",
                                     "You caught a brief view of the sunset before it disappeared into the horizon. 🌇",
                                     "You caught some warm rays of sunshine on your face. 🌞",
                                     "You caught what looks like an oversized moth larva. 🐛",
                                     "You caught a greasy soap dispenser. 🧼",
                                     "You caught a rusty oyster knife. 🗡️",
                                     "You caught a 20% off coupon for the local coffee shop. ☕",
                                     "You caught your breath. 😮‍💨",
                                     "You caught a baseball and have no idea where it came from. ⚾",
                                     "You took a second to daydream about all the sushi you're going to make with the fish you catch. 🍣",
                                     "You caught a northern pike. ",
                                     "You caught a haddock. ",
                                     "You caught a cod. ",
                                     "You caught a lungfish. ",
                                     "You caught a rockfish. ",
                                     "You caught the world's smallest megalodon. ",
                                     "You caught a gigantic catfish. 🐱",
                                     "You caught a zander. ",
                                     "You caught a chum salmon. ",
                                     "You caught a mahi-mahi. ",
                                     "You caught a bluegill. ",
                                     "You caught a snook. ",
                                     "You caught a japanese amberjack. ",
                                     "You caught a greater amberjack. ",
                                     "You caught an atlantic goliath grouper. ",
                                     "You caught a large bass. ",
                                     "You caught a albacore. ",
                                     "You caught a banjo catfish. 🪕",
                                     "You caught a brown trout. ",
                                     "You caught a bluegill. ",
                                     "You caught a bull shark. 🦈",
                                     "You caught a boxfish. ",
                                     "You caught a cobia. ",
                                     "You caught a chinook salmon. ",
                                     "You caught a cherry salmon. ",
                                     "You caught a coho salmon. ",
                                     "You caught a crappie. ",
                                     "You caught a dogfish. 🐶",
                                     "You caught a black drum. 🥁",
                                     "You caught a dusky grouper. ",
                                     "You caught a finback cat shark. ",
                                     "You caught a giant sea bass. ",
                                     "You caught a hagfish. 👵",
                                     "You caught a lemon shark. ",
                                     "You caught a northern pike. ",
                                     "You caught a pink salmon. ",
                                     "You caught a piranha. ",
                                     "You caught a pompano. ",
                                     "You caught a red snapper. ",
                                     "You caught a striped bass. ",
                                     "You caught a sailfish. ",
                                     "You caught a trunk fish. 🐘",
                                     "You caught a yellowfin tuna. ",
                                     "You caught a zebrafish. 🦓",
                                     "You caught life by the horns and you're not letting go for anything. 😈",
                                     "You caught a message in a bottle addressed to some body you've never heard of. 🍼",
                                     "You caught a tiger by his toe. 🐯",
                                     "You caught the earthy odor of pipe smoke, floating in the breeze. 😶‍🌫️",
                                     "You caught a sharp piece of plastic with many holes in it. ♯",
                                     "You caught a piece of old rope. ",
                                     "You caught a baseball cap, covered in algae. 🧢",
                                     "You lost your bait. ",
                                     "Your line snapped. ",
                                     "You feel like it might rain. 🌦️",
                                     "You wish it would rain. ☔",
                                     "You pulled up an old box of junk and set it aside. 🗃️",
                                     "You pulled up an old anchor. This thing is heavy! ⚓",
                                     "You caught a branch from a young elm tree. 🌳",
                                     "You caught news that the circus is coming to town. 🎪",
                                     "You caught a half-empty bottle of malt-liquor. 🍾",
                                     "You caught a jar of brown mayonaise. 🧴",
                                     "You caught a small collection of thimbles. 🗑️",
                                     "You caught some sort of snake carcass. 🐍",
                                     "You caught a what remains of a flag. 🏳️",
                                     "You caught a tail-light from an old truck. 🚨",
                                     "You caught a rotting squirrel carcass. 🐿️",
                                     "You caught a scuba diver. She snatched your pole and is beating you with it. 🤿",
                                     "You caught a fire mixtape. 🖭",
                                     "You caught a hankering to dance a little jig. 🕺🏽",
                                     "You caught a red herring made of plastic.",
                                     "You caught a piece of driftwood. 📏");
                
                
                 var random = bank1[Math.floor(Math.random() * bank1.length)];
                 let messText = document.getElementById("message");
                 messText.replaceChildren(random);
            }
            